-- RIGHT OUTER JOIN

-- Entre pessoa e contato
SELECT * 
	FROM PESSOA p 
	RIGHT OUTER JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA);

-- Pessoa, Pessoa_x_Pessoa_Endereco e Endereco_Pessoa 
SELECT *
	FROM PESSOA p
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO);

-- Todas as tabelas (Começando por pessoa)
SELECT *
	FROM PESSOA p
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
	RIGHT OUTER JOIN CONTATO c ON (c.ID_PESSOA  = p.ID_PESSOA);

-- FAZER O OUTER FULL JOIN

-- Entre pessoa e contato
SELECT * 
	FROM PESSOA p 
	FULL OUTER JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA);

-- Pessoa, Pessoa_x_Pessoa_Endereco e Endereco_Pessoa 
SELECT *
	FROM PESSOA p
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO);

-- Todas as tabelas (Começando por pessoa)
SELECT *
	FROM PESSOA p
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
	FULL OUTER JOIN CONTATO c ON (c.ID_PESSOA  = p.ID_PESSOA);

-- SELECIONAR AS PESSOAS QUE TEM ENDEREÇO
SELECT *
	FROM PESSOA p
WHERE EXISTS(
	SELECT pxpe.ID_PESSOA
	FROM PESSOA_X_PESSOA_ENDERECO pxpe
	WHERE pxpe.ID_PESSOA = P.ID_PESSOA
)


-- SELECIONAR ID, NOME, NOME DA TABELA PESSOA JUNTO COM ID, LOGRADOURO DA TABELA ENDEREÇO
-- Preferi fazer com left msm, e as informações solicitadas!!!

SELECT p.ID_PESSOA, 
	   p.NOME, p.ID_PESSOA ||' - '|| p.Nome ||' - '|| end_pess.LOGRADOURO AS Pessoa_ID_ENDERECO, 
	   end_pess.LOGRADOURO 
FROM PESSOA p
LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON pxpe.ID_PESSOA = p.ID_PESSOA
LEFT JOIN ENDERECO_PESSOA end_pess ON end_pess.ID_ENDERECO  = pxpe.ID_ENDERECO 