-- RIGHT OUTER JOIN

-- Entre pessoa e contato
SELECT * 
	FROM PESSOA p 
	RIGHT OUTER JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA);

-- Pessoa, Pessoa_x_Pessoa_Endereco e Endereco_Pessoa 
SELECT *
	FROM PESSOA p
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO);

-- Todas as tabelas (Começando por pessoa)
SELECT *
	FROM PESSOA p
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
	RIGHT OUTER JOIN CONTATO c ON (c.ID_PESSOA  = p.ID_PESSOA);

-- FAZER O OUTER FULL JOIN

-- Entre pessoa e contato
SELECT * 
	FROM PESSOA p 
	FULL OUTER JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA);

-- Pessoa, Pessoa_x_Pessoa_Endereco e Endereco_Pessoa 
SELECT *
	FROM PESSOA p
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO);

-- Todas as tabelas (Começando por pessoa)
SELECT *
	FROM PESSOA p
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
	FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
	FULL OUTER JOIN CONTATO c ON (c.ID_PESSOA  = p.ID_PESSOA);

-- SELECIONAR AS PESSOAS QUE TEM ENDEREÇO
SELECT *
	FROM PESSOA p
WHERE EXISTS(
	SELECT pxpe.ID_PESSOA
	FROM PESSOA_X_PESSOA_ENDERECO pxpe
	WHERE pxpe.ID_PESSOA = P.ID_PESSOA
)


-- SELECIONAR ID, NOME, NOME DA TABELA PESSOA JUNTO COM ID, LOGRADOURO DA TABELA ENDEREÇO
SELECT p.ID_PESSOA, p.Nome || p.ID_PESSOA, end_pess.Logradouro
FROM PESSOA p, ENDERECO_PESSOA end_pess 
WHERE 
EXISTS (
  SELECT * 
  FROM 
      PESSOA_X_PESSOA_ENDERECO pxpe  
  WHERE 
      p.ID_PESSOA = pxpe.ID_PESSOA
)